const homes = [
	{
		id: 0,
		name: 'Paulina',
		surname: 'Kowalska',
		location: 'Gdynia Redłowo',
		coordinates: [],
		pets: 1,
		mobile: 355344506,
		info: '',
		email: 'pkmail@gmail.com',
	},
	{
		id: 1,
		name: 'Daria',
		surname: 'Wieloch',
		location: 'Gdańsk Orunia',
		coordinates: [],
		pets: 0,
		mobile: 776356225,
		info: '',
		email: 'dwmail@gmail.com',
	},
	{
		id: 2,
		name: 'Agata',
		surname: 'Nowak',
		location: 'Gdynia Kowale',
		coordinates: [],
		pets: 1,
		mobile: 468946122,
		info: '',
		email: 'anmail@gmail.com',
	},
	{
		id: 3,
		name: 'Aleksandra',
		surname: 'Wójcik',
		location: 'Gdynia Śródmieście',
		coordinates: [],
		pets: 2,
		mobile: 468946122,
		info: '',
		email: 'awmail@gmail.com',
	},
	{
		id: 4,
		name: 'Anna',
		surname: 'Tleń',
		location: 'Gdańsk Wrzeszcz',
		coordinates: [],
		pets: 1,
		mobile: 468946122,
		info: '',
		email: 'atmail@gmail.com',
	},
	{
		id: 5,
		name: 'Miłosz',
		surname: 'Rylski',
		location: 'Gdańsk Wrzeszcz',
		coordinates: [],
		pets: 0,
		mobile: 468946122,
		info: '',
		email: 'mrmail@gmail.com',
	},
	{
		id: 6,
		name: 'Marcin',
		surname: 'Kubacki',
		location: 'Gdańsk Zaspa',
		coordinates: [],
		pets: 4,
		mobile: 468946122,
		info: '',
		email: 'mkmail@gmail.com',
	},
]
export { homes }
